DATA_FOLDER= "/home/nahuel/Documents/tesis/fine_tunning/data/sedici/"
JSON_FOLDER=DATA_FOLDER+"jsons/"
COLUMNS_DATA = ['id', 'title', 'abstract', 'categories','authors']
DATASET_FILENAME="metadata_sedici_files.json"
LOG_DIR = "./log"
BASE_MODEL="allenai/led-base-16384"
MAX_TOKENS_INPUT=16384
MAX_TOKENS_OUTPUT= 512 
FINAL_MODEL_PATH = "/fine-tuned-model"
CHECKPOINT_MODEL_PATH = "./results"